---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: "{{ ansible_os_family }}.yml"

- name: Redis configure
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: start and enable redis
  service: "name={{ redis_daemon }} state=started enabled=yes"
