---  
 - name: add user
   user: name={{ user }} shell=/bin/bash password={{ 'Kaishu@hadoop' |password_hash('sha512') }} update_password=always append=yes

 - name: Config /etc/sudoers
   lineinfile: dest=/etc/sudoers state=present  line='{{item}}' validate='visudo -cf %s'
   with_items:
          - "{{ user}} ALL=(ALL) NOPASSWD: ALL"
