---
- name: Configure core-site.xml
  template: dest="{{hadoop_home}}/etc/hadoop" src=core-site.xml owner=root group=root
  notify:
     - restart hadoop-dfs
     - restart yarn-resourcemanager
     - restart yarn-zkfc
     - restart datanode
     - restart journalnode
     - restart nodemanager

- name: Configure hdfs-site.xml
  template: dest="{{hadoop_home}}/etc/hadoop" src=hdfs-site.xml owner=root group=root
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart yarn-zkfc
   - restart datanode
   - restart journalnode
   - restart nodemanager

- name: Configure slaves
  template: dest="{{hadoop_home}}/etc/hadoop" src=slaves owner=root group=root
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart yarn-zkfc
   - restart datanode
   - restart journalnode
   - restart nodemanager

- name: Configure yarn-site.xml
  template: dest="{{hadoop_home}}/etc/hadoop" src=yarn-site.xml owner=root group=root
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart yarn-zkfc
   - restart datanode
   - restart journalnode
   - restart nodemanager

- name: Configure mapred-site.xml
  template: dest="{{hadoop_home}}/etc/hadoop" src=mapred-site.xml owner=root group=root
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart yarn-zkfc
   - restart datanode
   - restart journalnode
   - restart nodemanager

- name: Configure  hadoop-env.sh
  template: dest="{{hadoop_home}}/etc/hadoop" src=hadoop-env.sh owner=root group=root
  notify:
   -stop all
   -start all

- name: Configure yarn-env.sh
  template: dest="{{hadoop_home}}/etc/hadoop" src=yarn-env.sh owner=root group=root
  notify: 
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart yarn-zkfc
   - restart datanode
   - restart journalnode
   - restart nodemanager
