---
- name: "[EL] Fail if distro is not supported nor tested"
  fail: msg="The role is designed only for RedHat/CentOS 7.2 or later"
  when: "ansible_distribution not in ('RedHat', 'CentOS') or {{ ansible_distribution_version | version_compare('7.2', '<') }}"

- name: "[EL] Add Docker yum repository"
  copy:
    src=files/docker.repo dest=/etc/yum.repos.d/docker.repo mode=0644

- name: "[EL] Perform common tasks"
  include: common.yml

- name: "[EL] Configure docker daemon options"
  include: systemd.yml

