---
- hosts: zookeeper
  remote_user: root
  vars:
     - base_path: "/data/app"
     - package: "/etc/ansible/package/zookeeper-3.4.6.tar.gz"
     - zookeeper_data_dir: "/data/app/zookeeper-3.4.6/data"
     - zookeeper_log_dir: "/var/log/zookeeper"
     - zookeeper_dir: "/data/app/zookeeper-3.4.6"
     - zookeeper_conf_dir: "/data/app/zookeeper-3.4.6/conf"
     - status: "install"
  roles:
     - zookeeper

