---

#
# variables needed to be defined in user's playbook
#



#
# user-configurable defaults
#

nginx_version:            1.10.2    # will install the default (usually the latest stable) version, if not specified.
nginx_user:               nginx     # uid of worker process
nginx_status:             False     # install health-checking endpoint "http://HOST:PORT/nginx_status"?
nginx_ulimit:             204800    # worker_rlimit_nofile in nginx.conf
nginx_worker_connections: 20480     # worker_connections in nginx.conf

#---- the following vars are handled in tasks/set-role-variables.yml ------

#nginx_use_service:       True      # use "service" command to start/restart nginx?
#nginx_in_selinux:        False
