---
#have mixed feelings with the way i did this.
#Ideally i would only issue commands to filesystem and mount but i had
#issues with the previously configured raid setup.
#Going to make formatting and mounting optional

- name: Getting Filesystem Info
  shell:  " lsblk -f /dev/{{item}}  | grep 'ext4' "
  ignore_errors: True
  register: drive_info
  with_items: '{{hostvars[inventory_hostname]["ansible_devices"].keys()|sort}}'
  when: item != root_drive
  tags:
    - mounts
    - testingmounts

#Future task to check if mounted to a different path.
#should unmount from the specified path.
- name: Unmount Drives
  mount:
    name: /{{ hdfs_mount}}/{{item.item}}
    src: /dev/{{item.item}}"
    fstype: "{{ fstype }}"
    state: unmounted
  with_items: "{{ drive_info.results }}"
#  when: "the mount point is not /hdfs/<drive>"

- name: Test Mount
  debug: msg="Index of {{item.1}} is  {{item.0}}"
  with_indexed_items: "{{drive_info.results}}"
  tags:
    - testingmounts

- name: Format Drives
  filesystem:
    force: yes 
    dev: /dev/{{ item.item }} 
    fstype: "{{ fstype }}"
  with_items: "{{ drive_info.results }}"
  when: "item.item != root_drive and item.stdout == ''"
  tags:
    - mounts

- name: Mount Drives
  mount:
    name: /{{ hdfs_mount  }}/data{{item.index}}
    src: /dev/{{ item.item }}
    fstype: "{{ fstype }}"
    state: mounted
    opts: "noatime"
  with_items:  "{{ drive_info.results }}"
  when: "item.item != root_drive and item.changed and not '/{{hdfs_mount}}/{{item.item}}' in item.stdout" 
  tags:
    - mounts
