---
- name: install libselinux-python
  yum:
    name: libselinux-python
    state: present
  tags:
    - optimize
    - selinux

- name: turn off selinux
  selinux:
    state: disabled
  tags:
    - optimize
    - selinux
