---

- name: Copy kafka_tar_gz to client
  unarchive: src={{package}}  dest={{base_path}} owner=root group=root
  when: status == 'install'

- name: Configure kafka frofile
  shell: /bin/echo {{ item }} | sudo tee -a /etc/profile
  with_items:
   - ####KAFKA####
   - export KAFKA_HOME={{kafka_home}}
   - export PATH=\$KAFKA_HOME/bin:\$PATH

- name: copy start.sh
  template: dest="{{kafka_home}}/bin" src=start.sh owner=root group=root mode=0755

- name: copy stop.sh
  template: dest="{{kafka_home}}/bin" src=stop.sh owner=root group=root mode=0755

- name: Setup server.properties
  template: dest="{{kafka_home}}/config" src=server.properties owner=root group=root
  notify:
   - restart kafka

#- name: start kafka
#  action: shell {{kafka_home}}/bin/start.sh
#  when: status == 'install'

