---
- name: copy userparameter_diskstats.conf
  template: src=userparameter_diskstats.conf dest=/etc/zabbix/zabbix_agentd.d/

- name: copy lld-disks.py
  copy: src=lld-disks.py dest=/usr/local/bin/ mode=0755

- name: restart agent
  shell: systemctl restart zabbix-agent
