#- name: Install OpenJDK
#  yum: name=java-1.7.0-openjdk state=present

#- name: Change ownership on monasca download directory.
#  file: path="{{monasca_download_dir}}" state=directory owner=hadoop group=hadoop recurse=yes

#- name: Change ownership on zokeeper directory.
#  file: path="{{zookeeper_dir}}" state=directory owner=hadoop group=hadoop recurse=yes


#- name: Download Zookeeper version
#  get_url: url={{zookeeper_url}} dest={{monasca_download_dir}}/zookeeper-{{zookeeper_version}}.tar.gz timeout=100

#- name: Unpack tarball
#  command: tar xzf {{monasca_download_dir}}/zookeeper-{{zookeeper_version}}.tar.gz --strip-components=1 chdir={{zookeeper_dir}} creates={{zookeeper_dir}}/bin
- name: Copy zk_tar_gz to client
  unarchive: src=zookeeper-3.4.6.tar.gz  dest=/home/hadoop
- name: Install zookeeper
  file: path=/home/hadoop/zookeeper-3.4.6 owner=hadoop group=hadoop recurse=yes
- name: mkdir
  file: path=/home/hadoop/zookeeper-3.4.6/data state=directory owner=hadoop group=hadoop

- name: Setup Apache ZooKeeper service
  template: dest="/etc/init.d/zookeeper" src=zookeeper mode=0755 owner=hadoop group=hadoop
  register: zookeeper_service

- name: chkconfig zookeeper
  command: chkconfig --add /etc/init.d/zookeeper
  when: zookeeper_service | changed
